language: node_js

node_js:
  - "6.6.0"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

script:
  - npm --version
  - yarn --version
  - yarn install
  - npm run lint
  - npm run build

notifications:
  slack:
    on_success: always
    on_failure: always
